#![cfg_attr(not(feature = "std"), no_std, no_main)]

#[ink::contract]
pub mod multi_contract_caller {
    use accumulator::AccumulatorRef;
    use adder::AdderRef;
    use subber::SubberRef;

    /// Specifies the state of the `multi_contract_caller` contract.
    ///
    /// In `Adder` state the `multi_contract_caller` contract will call the `Adder`
    /// contract and in `Subber` state will call to the `Subber` contract.
    ///
    /// The initial state is `Adder`.
    #[derive(Debug, Copy, Clone, PartialEq, Eq)]
    #[ink::storage_item(packed)]
    pub enum Which {
        Adder,
        Subber,
    }

    /// Calls to an `adder` or `subber` contract to mutate a value in an `accumulator`
    /// contract.
    ///
    /// # Note
    ///
    /// In order to instantiate the `multi_contract_caller` smart contract we first
    /// have to manually put the code of the `accumulator`, `adder`
    /// and `subber` smart contracts, receive their code hashes from
    /// the signalled events and put their code hash into our
    /// `multi_contract_caller` smart contract.
    ///
    /// The `AccumulatorRef`, `AdderRef` and `SubberRef` are smart contract
    /// reference types that have been automatically generated by ink!.
    #[ink(storage)]
    pub struct MultiContractCaller {
        /// Says which of `adder` or `subber` is currently in use.
        which: Which,
        /// The `accumulator` smart contract.
        accumulator: AccumulatorRef,
        /// The `adder` smart contract.
        adder: AdderRef,
        /// The `subber` smart contract.
        subber: SubberRef,
    }

    impl MultiContractCaller {
        /// Instantiate a `multi_contract_caller` contract with the given sub-contract
        /// codes.
        #[ink(constructor, payable)]
        pub fn new(
            init_value: i32,
            version: u32,
            accumulator_code_hash: ink::H256,
            adder_code_hash: ink::H256,
            subber_code_hash: ink::H256,
        ) -> Self {
            let total_balance = Self::env().balance();
            let one_fourth = total_balance.checked_div(4.into()).expect("div failed");

            let salt = salt_from_version(version);
            let accumulator = AccumulatorRef::new(init_value)
                .endowment(one_fourth)
                .code_hash(accumulator_code_hash)
                .salt_bytes(salt)
                .instantiate();
            let adder = AdderRef::new(accumulator.clone())
                .endowment(one_fourth)
                .code_hash(adder_code_hash)
                .salt_bytes(salt)
                .instantiate();
            let subber = SubberRef::new(accumulator.clone())
                .endowment(one_fourth)
                .code_hash(subber_code_hash)
                .salt_bytes(salt)
                .instantiate();
            Self {
                which: Which::Adder,
                accumulator,
                adder,
                subber,
            }
        }

        /// Returns the `accumulator` value.
        #[ink(message)]
        pub fn get(&self) -> i32 {
            self.accumulator.get()
        }

        /// Delegates the call to either `Adder` or `Subber`.
        #[ink(message)]
        pub fn change(&mut self, by: i32) {
            match self.which {
                Which::Adder => self.adder.inc(by),
                Which::Subber => self.subber.dec(by),
            }
        }

        /// Switches the `multi_contract_caller` contract.
        #[ink(message)]
        pub fn switch(&mut self) {
            match self.which {
                Which::Adder => {
                    self.which = Which::Subber;
                }
                Which::Subber => {
                    self.which = Which::Adder;
                }
            }
        }
    }

    fn salt_from_version(version: u32) -> Option<[u8; 32]> {
        let version: [u8; 4] = version.to_le_bytes();
        let mut salt: [u8; 32] = [0u8; 32];
        salt[..4].copy_from_slice(&version);
        Some(salt)
    }
}

#[cfg(test)]
mod tests;