#![cfg_attr(not(feature = "std"), no_std)]

#[ink::contract]
mod delegator {
    use accumulator::AccumulatorRef;
    use adder::AdderRef;
    use subber::SubberRef;

    /// Specifies the state of the `delegator` contract.
    ///
    /// In `Adder` state the `delegator` contract will delegate to the `Adder` contract
    /// and in `Subber` state will delegate to the `Subber` contract.
    ///
    /// The initial state is `Adder`.
    #[derive(Debug, Copy, Clone, PartialEq, Eq, scale::Decode, scale::Encode)]
    #[cfg_attr(
        feature = "std",
        derive(ink::storage::traits::StorageLayout, scale_info::TypeInfo)
    )]
    pub enum Which {
        Adder,
        Subber,
    }

    /// Delegates calls to an `adder` or `subber` contract to mutate
    /// a value in an `accumulator` contract.
    ///
    /// # Note
    ///
    /// In order to instantiate the `delegator` smart contract we first
    /// have to manually put the code of the `accumulator`, `adder`
    /// and `subber` smart contracts, receive their code hashes from
    /// the signalled events and put their code hash into our
    /// `delegator` smart contract.
    ///
    /// The `AccumulatorRef`, `AdderRef` and `SubberRef` are smart contract
    /// reference types that have been automatically generated by ink!.
    #[ink(storage)]
    pub struct Delegator {
        /// Says which of `adder` or `subber` is currently in use.
        which: Which,
        /// The `accumulator` smart contract.
        accumulator: AccumulatorRef,
        /// The `adder` smart contract.
        adder: AdderRef,
        /// The `subber` smart contract.
        subber: SubberRef,
    }

    impl Delegator {
        /// Instantiate a `delegator` contract with the given sub-contract codes.
        #[ink(constructor)]
        pub fn new(
            init_value: i32,
            version: u32,
            accumulator_code_hash: Hash,
            adder_code_hash: Hash,
            subber_code_hash: Hash,
        ) -> Self {
            let total_balance = Self::env().balance();
            let salt = version.to_le_bytes();
            let accumulator = AccumulatorRef::new(init_value)
                .endowment(total_balance / 4)
                .code_hash(accumulator_code_hash)
                .salt_bytes(salt)
                .instantiate()
                .unwrap_or_else(|error| {
                    panic!(
                        "failed at instantiating the Accumulator contract: {:?}",
                        error
                    )
                });
            let adder = AdderRef::new(accumulator.clone())
                .endowment(total_balance / 4)
                .code_hash(adder_code_hash)
                .salt_bytes(salt)
                .instantiate()
                .unwrap_or_else(|error| {
                    panic!("failed at instantiating the Adder contract: {:?}", error)
                });
            let subber = SubberRef::new(accumulator.clone())
                .endowment(total_balance / 4)
                .code_hash(subber_code_hash)
                .salt_bytes(salt)
                .instantiate()
                .unwrap_or_else(|error| {
                    panic!("failed at instantiating the Subber contract: {:?}", error)
                });
            Self {
                which: Which::Adder,
                accumulator,
                adder,
                subber,
            }
        }

        /// Returns the `accumulator` value.
        #[ink(message)]
        pub fn get(&self) -> i32 {
            self.accumulator.get()
        }

        /// Delegates the call to either `Adder` or `Subber`.
        #[ink(message)]
        pub fn change(&mut self, by: i32) {
            match self.which {
                Which::Adder => self.adder.inc(by),
                Which::Subber => self.subber.dec(by),
            }
        }

        /// Switches the `delegator` contract.
        #[ink(message)]
        pub fn switch(&mut self) {
            match self.which {
                Which::Adder => {
                    self.which = Which::Subber;
                }
                Which::Subber => {
                    self.which = Which::Adder;
                }
            }
        }
    }

    #[cfg(test)]
    mod e2e_tests {
        use ink::env::e2e::*;

        type E2EResult<T> = std::result::Result<T, Box<dyn std::error::Error>>;

        #[ink::e2e_test]
        async fn e2e_sending_value_to_give_me_must_fail(
            mut client: ink::env::e2e::Client<C, E>,
        ) -> E2EResult<()> {
            // given
            //ink::env::import!("target/ink/accumulator/accumulator.contract");

            ink::env::build!("target/ink/accumulator/accumulator.contract");
            let _accumuluator_acc_id = client
                .upload(&mut ink::env::e2e::alice(), constructor, 9, None)
                .await
                .expect("instantiate failed")
                .account_id;
            /*
            let accumulator_hash = accumulator::_ink_hash;
            let contract_bundle = accumulator::_ink_contract_path;
            let metadata = ink::env::e2e::metadata(contract_bundle);
            let accumulator_hash = metadata.source.hash;
            let accumulator_hash: delegator::contract_types::ink_primitives::types::Hash

            ink::env::build!("target/ink/subber/subber.contract");
            let subber_hash = subber::_ink_hash;
            let contract_bundle = subber::_ink_contract_path;
            let metadata = ink::env::e2e::metadata(contract_bundle);
            let subber_hash = metadata.source.hash;

            ink::env::build!("target/ink/adder/adder.contract");
            let adder_hash = subber::_ink_hash;
            let contract_bundle = adder::_ink_contract_path;
            let metadata = ink::env::e2e::metadata(contract_bundle);
            let adder_hash = metadata.source.hash;
            */

            /*
            let constructor = accumulator::constructors::new(123 as i32);
            let _accumuluator_acc_id = client
                .instantiate(&mut ink::env::e2e::alice(), constructor, 9, None)
                .await
                .expect("instantiate failed")
                .account_id;
             */

           //let _hash: Hash = accumuluator::_ink_metadata().hash(),
            //let _hash = ink::env::e2e::extract_hash_from_contract_bundle(accumulator::_ink_contract_path);

            /*
            let constructor = delegator::constructors::new(
                1234, // initial value
                1337, // salt
                accumulator_hash,
                adder_hash,
                subber_hash,
            );

            let _delegator_acc_id = client
                .instantiate(&mut ink::env::e2e::alice(), constructor, 0, None)
                .await
                .expect("instantiate failed")
                .account_id;
             */

            /*

            // when
            let transfer = contract_transfer::messages::give_me(120);
            let call_res = client
                .call(
                    &mut ink::env::e2e::bob(),
                    contract_acc_id.clone(),
                    transfer.into(),
                    10,
                    None,
                )
                .await;

            // then
            assert!(call_res.is_err());
            let contains_err_msg = match call_res.unwrap_err() {
                ink::env::e2e::Error::CallDryRun(dry_run) => {
                    String::from_utf8_lossy(&dry_run.debug_message)
                        .contains("paid an unpayable message")
                }
                _ => false,
            };
            assert!(contains_err_msg);
             */
            Ok(())
        }
    }
}
